### ISSUE TITLE
Doesn't output status

### ISSUE THREAD

**Issue by greduan** [yonchu/zsh-vcs-prompt#1]
Hi, I recently came upon this by chance when glancing the issues in the [zsh-git-prompt](https://github.com/olivierverdier/zsh-git-prompt) repo.

My problem is the following:

I have everything setup correctly, but for some odd reason, it doesn't output anything.

Here's the important stuff in my `.zshrc` file:

``` sh
# Load Git prompt
source ~/.zsh/zsh-vcs-prompt/zshrc.sh

# Initialize colors.
autoload -U colors
colors

# Use shell script instead of Python
ZSH_VCS_PROMPT_USING_PYTHON='false'

# Allow for functions in the prompt.
setopt PROMPT_SUBST

# Set the prompt
PROMPT=$'%{${fg[yellow]}%}[%T] '  # Yellow color, current time
PROMPT+='%{${fg[cyan]}%}%~'       # Cyan color, current directory, from $HOME
PROMPT+='%{${fg[default]}%}$(vcs_info)' # Default color, Git status
PROMPT+='%{${fg[default]}%} >>> ' # Default color, prompt

# Set the right side of my prompt
RPROMPT=$'%{${fg[default]}%}[%n' # Default color, current user
RPROMPT+='@%m]' # Current server
```

Everything works fine except that it doesn't output anything. No errors no nothing, what am I missing? I use Git, and [zsh-git-prompt](https://github.com/olivierverdier/zsh-git-prompt) works fine, but this doesn't.

For my full dotfiles check my dotfiles repo: https://github.com/Greduan/dotfiles

Thanks for your help.

**Comment by yonchu** [comment]
Hi.

There was a typo in `README.md`.
Sorry for that.

Fix your `.zshrc` as follows:

``` sh
- PROMPT+='%{${fg[default]}%}$(vcs_info)' # Default color, Git status
+ PROMPT+='%{${fg[default]}%}$(vcs_super_info)' # Default color, Git status
```

**Comment by greduan** [comment]
Thanks! That fixed it! But now I have another problem, for which I will create another issue.

Thanks for your quick answer. :)
