### ISSUE TITLE
Customizing output

### ISSUE THREAD

**Issue by greduan** [yonchu/zsh-vcs-prompt#3]
On line [#102](https://github.com/yonchu/zsh-vcs-prompt/blob/master/zshrc.sh#L102) of the `zshrc.sh` file there is the following:

``` sh
echo "(${VCS_NAME_COLOR_USING_PYTHON}git%{${reset_color}%})-[${git_status}]"
```

Would there be an easy way to customize this without modifying the source? But rather set a variable in our `.zshrc` file, which defines the output?

This is just one idea that comes to me. :)

**Comment by greduan** [comment]
To clarify, I will give examples, the `~/dotfiles` is just an extra to demonstrate.

Right now it outputs something like this:
`~/dotfiles (git)-[master|✚ 1]`

How could I change this to:
`~/dotfiles [git](master|✚ 1)`

This is just an example. How would I configure this? And how would I do this from my `.zshrc` file, instead of modifying the `zshrc.sh` file.

If this isn't yet possible, how much would it take to implement it?

**Comment by yonchu** [comment]
I've implemented "customizing output" on the new branch "customizing-output".

You can change the symbols, the colors and output formats in your .zshrc file.

But it is still currently under consideration. :)

**Comment by greduan** [comment]
Excellent! Thanks!

Although, for some reason it doesn't work. :neutral_face: 
I have the following in my `.zshrc` file:

``` sh
# Git.
ZSH_VCS_PROMPT_GIT_FORMATS=${ZSH_VCS_PROMPT_GIT_FORMATS:-' (%s)[%b%c%d|%e%f%g%h%i%j]'}
ZSH_VCS_PROMPT_GIT_ACTION_FORMATS=${ZSH_VCS_PROMPT_GIT_ACTION_FORMATS:-' (%s)[%b:%a%c%d|%e%f%g%h%i%j]'}
# Other vcs.
ZSH_VCS_PROMPT_VCS_FORMATS=${ZSH_VCS_PROMPT_VCS_FORMATS:-' (%s)[%b]'}
ZSH_VCS_PROMPT_VCS_ACTION_FORMATS=${ZSH_VCS_PROMPT_VCS_ACTION_FORMATS:-' (%s)[%b:%a]'}

## The symbols.
ZSH_VCS_PROMPT_AHEAD_SIGIL=${ZSH_VCS_PROMPT_AHEAD_SIGIL:-'↑'}
ZSH_VCS_PROMPT_BEHIND_SIGIL=${ZSH_VCS_PROMPT_BEHIND_SIGIL:-'↓'}
ZSH_VCS_PROMPT_STAGED_SIGIL=${ZSH_VCS_PROMPT_STAGED_SIGIL:-'●'}
ZSH_VCS_PROMPT_CONFLICTS_SIGIL=${ZSH_VCS_PROMPT_CONFLICTS_SIGIL:-'✖'}
ZSH_VCS_PROMPT_UNSTAGED_SIGIL=${ZSH_VCS_PROMPT_UNSTAGED_SIGIL:-'✚'}
ZSH_VCS_PROMPT_UNTRACKED_SIGIL=${ZSH_VCS_PROMPT_UNTRACKED_SIGIL:-'…'}
ZSH_VCS_PROMPT_STASHED_SIGIL=${ZSH_VCS_PROMPT_STASHED_SIGIL:-'⚑'}
ZSH_VCS_PROMPT_CLEAN_SIGIL=${ZSH_VCS_PROMPT_CLEAN_SIGIL:-'✔ '}
```

But any output it gives is still the exact same. I tried sourcing the `zshrc.sh` file before and after these options, and it doesn't make a difference.

Does it make a difference for you? If so then maybe there's something wrong with my setup. Yes I have switched branches BTW. :wink:

Thanks for looking into this. Really appreciate it, and I'm sure others will too. :smile:

**Comment by yonchu** [comment]
Thank you for trying.

When you configure it in `.zshrc` file, set the following:

``` sh
# Git.
ZSH_VCS_PROMPT_GIT_FORMATS=' (%s)[%b%c%d|%e%f%g%h%i%j]'
ZSH_VCS_PROMPT_GIT_ACTION_FORMATS=' (%s)[%b:%a%c%d|%e%f%g%h%i%j]'
# Other vcs.
ZSH_VCS_PROMPT_VCS_FORMATS=' (%s)[%b]'
ZSH_VCS_PROMPT_VCS_ACTION_FORMATS=' (%s)[%b:%a]'

## The symbols.
ZSH_VCS_PROMPT_AHEAD_SIGIL='↑'
ZSH_VCS_PROMPT_BEHIND_SIGIL='↓'
ZSH_VCS_PROMPT_STAGED_SIGIL='●'
ZSH_VCS_PROMPT_CONFLICTS_SIGIL='✖'
ZSH_VCS_PROMPT_UNSTAGED_SIGIL='✚'
ZSH_VCS_PROMPT_UNTRACKED_SIGIL='…'
ZSH_VCS_PROMPT_STASHED_SIGIL='⚑'
ZSH_VCS_PROMPT_CLEAN_SIGIL='✔ '
```

It is OK to write it anywhere in `.zshrc` file.
I think it works.

**Just for information:**

``` sh
ZSH_VCS_PROMPT_AHEAD_SIGIL=${ZSH_VCS_PROMPT_AHEAD_SIGIL:-'↑'}
```

The above code is the same as the following code.

``` sh
if [ -z "$ZSH_VCS_PROMPT_AHEAD_SIGIL" ]; then
    ZSH_VCS_PROMPT_AHEAD_SIGIL=$ZSH_VCS_PROMPT_AHEAD_SIGIL
else
    ZSH_VCS_PROMPT_AHEAD_SIGIL='↑'
fi
```

**Comment by greduan** [comment]
OK, thanks. I tried what you gave me, copy&paste.

But it didn't work. Again, I tried sourcing both before and after the settings.

Does it work for you?

**Comment by yonchu** [comment]
Sorry, I do not know why it does not work.
I trie to run zsh with only the following settings (in .zshrc):

``` sh
# Git.
ZSH_VCS_PROMPT_GIT_FORMATS=' (!!%s)[%b%c%d|%e%f%g%h%i%j]'
ZSH_VCS_PROMPT_GIT_ACTION_FORMATS=' (%s)[%b:%a%c%d|%e%f%g%h%i%j]'
# Other vcs.
ZSH_VCS_PROMPT_VCS_FORMATS=' (%s)[%b]'
ZSH_VCS_PROMPT_VCS_ACTION_FORMATS=' (%s)[%b:%a]'

## The symbols.
ZSH_VCS_PROMPT_AHEAD_SIGIL='↑'
ZSH_VCS_PROMPT_BEHIND_SIGIL='↓'
ZSH_VCS_PROMPT_STAGED_SIGIL='●'
ZSH_VCS_PROMPT_CONFLICTS_SIGIL='✖'
ZSH_VCS_PROMPT_UNSTAGED_SIGIL='✚'
ZSH_VCS_PROMPT_UNTRACKED_SIGIL='…'
ZSH_VCS_PROMPT_STASHED_SIGIL='⚑'
ZSH_VCS_PROMPT_CLEAN_SIGIL='✔ '

# Load Git prompt
source ~/.zsh/zsh-vcs-prompt/zshrc.sh

# Initialize colors.
autoload -U colors
colors

# Use shell script instead of Python
ZSH_VCS_PROMPT_USING_PYTHON='false'

# Allow for functions in the prompt.
setopt PROMPT_SUBST


# Set the prompt
PROMPT=$'%{${fg[yellow]}%}[%T] '  # Yellow color, current time
PROMPT+='%{${fg[cyan]}%}%~'       # Cyan color, current directory, from $HOME
PROMPT+='%{${fg[default]}%}$(vcs_super_info)' # Default color, Git status
PROMPT+='%{${fg[default]}%} >>> ' # Default color, prompt

echo "Loaded .zshrc (zsh version $ZSH_VERSION)"
```

Here is my screenshot.
![screenshot](https://gist.github.com/raw/e8e9103feec3a9a4fc74/72d6400f67ac66f13017a3c086f02ada555250e7/screen_shot.png)

It seems that it work correctly.

**Comment by greduan** [comment]
I tried that, exactly as you gave it to me, and it doesn't work. :(

Maybe it depends on your Zsh version? Or Python version, who knows. :|

**Comment by yonchu** [comment]
If you set `ZSH_VCS_PROMPT_USING_PYTHON='false'`, Python is not used.
So, it could be due to the version of zsh.

What is the version of zsh you are using?

**Comment by greduan** [comment]
It tells me `zsh 4.3.11 (i386-apple-darwin12.0)`. And just in case, my Python version is `Python 2.7.2`.

**Comment by yonchu** [comment]
That's odd.

Look at this screenshot.
I tried to run zsh in the same version.

![screenshot](https://gist.github.com/raw/e8e9103feec3a9a4fc74/0dc5f84966f199bd88ffd48a18d6a0c0dee865ec/screen_shot_zsh411.png)

Could you provide your screenshot? If possible.
I want to see how it is actually displayed on your zsh.

**Comment by greduan** [comment]
Here's my screenshot: http://content.screencast.com/users/Eduan/folders/Default/media/59d84d81-73c1-488d-b0f6-c0ede20c0936/Screen%20Shot%202012-12-07%20at%2010.52.46%20AM.png

Sorry, I don't know how to embed screenshots in Markdown. ;)

**Comment by yonchu** [comment]
When you modified the source (zsh-vcs-prompt/zshrc.sh), your zsh prompt changes correctly?

For example, modify `zshrc.sh` as follows:

``` sh
ZSH_VCS_PROMPT_GIT_FORMATS=${ZSH_VCS_PROMPT_GIT_FORMATS:-'(%s)-[%b%c%d|%e%f%g%h%i%j]'}
↓
ZSH_VCS_PROMPT_GIT_FORMATS=${ZSH_VCS_PROMPT_GIT_FORMATS:-'(!!%s)-[%b%c%d|%e%f%g%h%i%j]'}
```

Does it work properly?

---

A way to embed images in Markdown. :smile: 

```
![Alt text](url)
```

**Comment by greduan** [comment]
Strangely, no!

What is going on? I'm not doing anything wrong am I?

Could you check my dotfiles to make sure there's nothing wrong?

**Comment by yonchu** [comment]
I checked your dotfiles, but it seems that there are no problems in particular.

You possibly don't switch the branch `customizing-output`?

Could you try calmly the following procedure once again?

```
$ cd ~/.zsh
$ git clone git://github.com/yonchu/zsh-vcs-prompt.git
$ cd zsh-vcs-prompt
$ git checkout -b customizing-output origin/customizing-output
$ echo "ZSH_VCS_PROMPT_GIT_FORMATS='(@%s)-[%b%c%d|%e%f%g%h%i%j]'" >> zshrc.sh
```

And then configures the following settings in your .zshrc.

``` sh
ZSH_VCS_PROMPT_GIT_FORMATS='(@%s)-[%b%c%d|%e%f%g%h%i%j]'

# Load Git prompt
source ~/.zsh/zsh-vcs-prompt/zshrc.sh

# Initialize colors.
autoload -U colors
colors

# Use shell script instead of Python
ZSH_VCS_PROMPT_USING_PYTHON='false'

# Allow for functions in the prompt.
setopt PROMPT_SUBST

# Set the prompt
PROMPT=$'%{${fg[yellow]}%}[%T] '  # Yellow color, current time
PROMPT+='%{${fg[cyan]}%}%~'       # Cyan color, current directory, from $HOME
PROMPT+='%{${fg[default]}%}$(vcs_super_info)' # Default color, Git status
PROMPT+='%{${fg[default]}%} >>> ' # Default color, prompt

echo "Loaded .zshrc (zsh version $ZSH_VERSION)"
```

And then reboot zsh.

If your zsh prompt should display as follows, it works correctly.

```
[4:52] ~/dotfiles (@git)-[master] >>> 
```

**Comment by greduan** [comment]
It worked! I have no idea what could have been the problem.

My branch was correct (I checked), but maybe something was wrong there... Because I didn't even need to change my settings, only needed to follow the Git steps.

In any case, I'm very sorry for causing so much trouble.

It works flawlessly, and I tip my hat to you, for your patience and ability. :smile:

**Comment by yonchu** [comment]
Not at all. Don't mention it.
I am relieved to hear that. :smile:
