### ISSUE TITLE
Update readme to explain difference between the python and shell script

### ISSUE THREAD

**Issue by expez** [yonchu/zsh-vcs-prompt#7]
It would be nice if the readme explained why one would choose the python script over the shell script.

The shell script is the more portable solution (as it has no dependencies), so there has to be some benefit to using the python script, right?

**Comment by yonchu** [comment]
Thank you for your advice. :smile:

I am sorry if my English is hard to understand. :sweat_smile:
Please feel free to point it out if there are any mistakes and improvements,
